CREATE TABLE category_info (
  id INT AUTO_INCREMENT
    PRIMARY KEY,
  book_category VARCHAR(200),
  book_count BIGINT
);
INSERT INTO category_info(book_category, book_count) VALUES ('.NET', 88);
INSERT INTO category_info(book_category, book_count) VALUES ('.NET, Big Data', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('.NET, Datebases', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('.NET, Hardware & DIY', 5);
INSERT INTO category_info(book_category, book_count) VALUES ('.NET, Windows', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('.NET, XML', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('3D Graphics', 42);
INSERT INTO category_info(book_category, book_count) VALUES ('3D Printing', 13);
INSERT INTO category_info(book_category, book_count) VALUES ('ActionScript', 13);
INSERT INTO category_info(book_category, book_count) VALUES ('Administration', 8);
INSERT INTO category_info(book_category, book_count) VALUES ('AI & Machine Learning', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Algorithms', 26);
INSERT INTO category_info(book_category, book_count) VALUES ('Algorithms, Data Mining', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Android', 121);
INSERT INTO category_info(book_category, book_count) VALUES ('Android, Game Programming', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Android, Game Programming, iOS', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Android, Security, Administration', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Android, Wireless Networks', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('AngularJS', 21);
INSERT INTO category_info(book_category, book_count) VALUES ('Apps', 46);
INSERT INTO category_info(book_category, book_count) VALUES ('ASP.NET', 101);
INSERT INTO category_info(book_category, book_count) VALUES ('ASP.NET, .NET', 4);
INSERT INTO category_info(book_category, book_count) VALUES ('ASP.NET, C#', 4);
INSERT INTO category_info(book_category, book_count) VALUES ('ASP.NET, C#, .NET', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('ASP.NET, HTML, HTML5 & CSS', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('ASP.NET, Network Administration', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('ASP.NET, Visual Basic, .NET', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('ASP.NET, XML', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Backbone.js', 10);
INSERT INTO category_info(book_category, book_count) VALUES ('Big Data', 76);
INSERT INTO category_info(book_category, book_count) VALUES ('Bootstrap', 9);
INSERT INTO category_info(book_category, book_count) VALUES ('Business Applications', 7);
INSERT INTO category_info(book_category, book_count) VALUES ('C & C++', 159);
INSERT INTO category_info(book_category, book_count) VALUES ('C & C++, .NET', 13);
INSERT INTO category_info(book_category, book_count) VALUES ('C & C++, .NET, Hardware & DIY', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('C & C++, Algorithms', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('C & C++, Android', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('C & C++, C#', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('C & C++, C#, .NET', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('C & C++, Delphi', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('C & C++, Game Programming', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('C & C++, Game Programming, Cloud & Virtualization', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('C & C++, Linux & Unix', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('C#', 116);
INSERT INTO category_info(book_category, book_count) VALUES ('C#, .NET', 10);
INSERT INTO category_info(book_category, book_count) VALUES ('C#, Game Programming', 4);
INSERT INTO category_info(book_category, book_count) VALUES ('C#, Windows', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('CAD', 28);
INSERT INTO category_info(book_category, book_count) VALUES ('Certification', 108);
INSERT INTO category_info(book_category, book_count) VALUES ('Cisco', 17);
INSERT INTO category_info(book_category, book_count) VALUES ('Clojure', 19);
INSERT INTO category_info(book_category, book_count) VALUES ('Cloud & Virtualization', 115);
INSERT INTO category_info(book_category, book_count) VALUES ('Cloud Computing', 55);
INSERT INTO category_info(book_category, book_count) VALUES ('Cloud Computing, Big Data', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Cloud Computing, Certification', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Cloud Computing, Network Administration', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Cloud Computing, Network Administration, Networks, Protocols & APIs', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Cloud Computing, Network Security', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Cloud Computing, Networks, Protocols & APIs', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Cloud Computing, Office', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Cloud Computing, Software', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('CMS', 179);
INSERT INTO category_info(book_category, book_count) VALUES ('CMS, Marketing & SEO', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Communications', 7);
INSERT INTO category_info(book_category, book_count) VALUES ('Computer Science', 199);
INSERT INTO category_info(book_category, book_count) VALUES ('Computer Science, Data Processing', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Computers & Technology', 24);
INSERT INTO category_info(book_category, book_count) VALUES ('Computers & Technology, Computer Science', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Data Analysis', 51);
INSERT INTO category_info(book_category, book_count) VALUES ('Data in the Enterprise', 8);
INSERT INTO category_info(book_category, book_count) VALUES ('Data in the Enterprise, Microsoft', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Data Mining', 35);
INSERT INTO category_info(book_category, book_count) VALUES ('Data Processing', 57);
INSERT INTO category_info(book_category, book_count) VALUES ('Data Processing, Data Mining', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases', 144);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases, Administration', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases, Algorithms', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases, Certification', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases, Cloud Computing', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases, Computer Science', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases, Data Mining', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases, Game Programming', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases, Graphics & Design', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases, Network Administration', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases, Security', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Datebases, Software', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Delphi', 3);
INSERT INTO category_info(book_category, book_count) VALUES ('Dreamweaver', 18);
INSERT INTO category_info(book_category, book_count) VALUES ('Ember.js', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Enterprise', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('ERP & CRM', 54);
INSERT INTO category_info(book_category, book_count) VALUES ('Express.js', 7);
INSERT INTO category_info(book_category, book_count) VALUES ('Ext JS', 7);
INSERT INTO category_info(book_category, book_count) VALUES ('Flash', 6);
INSERT INTO category_info(book_category, book_count) VALUES ('Front-End Frameworks', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Game Programming', 281);
INSERT INTO category_info(book_category, book_count) VALUES ('Game Programming, iOS', 3);
INSERT INTO category_info(book_category, book_count) VALUES ('Game Programming, iOS, Swift', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Graphics & Design', 88);
INSERT INTO category_info(book_category, book_count) VALUES ('Graphics & Design, Administration', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Graphics & Design, Computer Science', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Graphics & Design, Game Programming', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Graphics & Design, jQuery', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Groovy', 13);
INSERT INTO category_info(book_category, book_count) VALUES ('GUI', 20);
INSERT INTO category_info(book_category, book_count) VALUES ('Hardware & DIY', 241);
INSERT INTO category_info(book_category, book_count) VALUES ('Hardware & DIY, Certification', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Hardware & DIY, Computer Science', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Hardware & DIY, Network Administration', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Hardware & DIY, Network Security', 4);
INSERT INTO category_info(book_category, book_count) VALUES ('Hardware & DIY, Networking & Cloud Computing', 5);
INSERT INTO category_info(book_category, book_count) VALUES ('Hardware & DIY, Networks, Protocols & APIs', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Hardware & DIY, Wireless Networks', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('HTML, HTML5 & CSS', 186);
INSERT INTO category_info(book_category, book_count) VALUES ('HTML, HTML5 & CSS, .NET', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('HTML, HTML5 & CSS, Apps', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('HTML, HTML5 & CSS, Dreamweaver', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('HTML, HTML5 & CSS, Game Programming', 4);
INSERT INTO category_info(book_category, book_count) VALUES ('HTML, HTML5 & CSS, JavaScript', 5);
INSERT INTO category_info(book_category, book_count) VALUES ('HTML, HTML5 & CSS, JavaScript, Game Programming', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('HTML, HTML5 & CSS, JavaScript, iOS', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('HTML, HTML5 & CSS, PHP, jQuery', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Illustrator', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Infrastructure', 8);
INSERT INTO category_info(book_category, book_count) VALUES ('Internet & Social Media', 3);
INSERT INTO category_info(book_category, book_count) VALUES ('iOS', 207);
INSERT INTO category_info(book_category, book_count) VALUES ('iOS, Swift', 5);
INSERT INTO category_info(book_category, book_count) VALUES ('Java', 398);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Algorithms', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Android', 4);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Certification', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Data Mining', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Datebases', 5);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Game Programming', 6);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Graphics & Design', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Hardware & DIY', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Network Administration', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Networking & Cloud Computing', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Oracle', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Security', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, Services & APIs', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, SQL', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Java, XML', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript', 248);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, 3D Graphics', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, Apps', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, C & C++', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, Datebases', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, Game Programming, 3D Graphics', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, Java', 7);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, jQuery, AngularJS', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, MongoDB', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, Network Administration', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, Network Security', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, PHP', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, Python, Ruby', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('JavaScript, Visual Basic', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('jQuery', 50);
INSERT INTO category_info(book_category, book_count) VALUES ('Linux', 3);
INSERT INTO category_info(book_category, book_count) VALUES ('Linux & Unix', 175);
INSERT INTO category_info(book_category, book_count) VALUES ('Linux & Unix, Hardware & DIY', 3);
INSERT INTO category_info(book_category, book_count) VALUES ('Linux & Unix, Macintosh', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Linux & Unix, Network Administration', 10);
INSERT INTO category_info(book_category, book_count) VALUES ('Linux & Unix, Networking & Cloud Computing', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Linux & Unix, Security', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Mac', 24);
INSERT INTO category_info(book_category, book_count) VALUES ('Macintosh', 19);
INSERT INTO category_info(book_category, book_count) VALUES ('Macintosh, Hardware & DIY', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Macintosh, iOS', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Macintosh, Swift', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Mail Servers', 11);
INSERT INTO category_info(book_category, book_count) VALUES ('Marketing & SEO', 60);
INSERT INTO category_info(book_category, book_count) VALUES ('Maya', 4);
INSERT INTO category_info(book_category, book_count) VALUES ('Maya, 3D Graphics', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Messaging', 11);
INSERT INTO category_info(book_category, book_count) VALUES ('Microsoft', 6);
INSERT INTO category_info(book_category, book_count) VALUES ('Microsoft Platform', 10);
INSERT INTO category_info(book_category, book_count) VALUES ('MongoDB', 7);
INSERT INTO category_info(book_category, book_count) VALUES ('MongoDB, Cloud Computing', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('MongoDB, Network Administration', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Monitoring', 10);
INSERT INTO category_info(book_category, book_count) VALUES ('MySQL', 37);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Administration', 103);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Administration, Apps', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Administration, Certification', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Administration, Cisco', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Administration, Computer Science', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Administration, Data Mining', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Administration, Data Processing, Data Mining', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Administration, Network Security', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Administration, Networks, Protocols & APIs', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Administration, Office', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Security', 35);
INSERT INTO category_info(book_category, book_count) VALUES ('Network Security, Security', 4);
INSERT INTO category_info(book_category, book_count) VALUES ('Networking & Cloud Computing', 294);
INSERT INTO category_info(book_category, book_count) VALUES ('Networking & Cloud Computing, Certification', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Networking & Cloud Computing, Cisco', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Networking & Cloud Computing, Computer Science', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Networking & Cloud Computing, Data Processing', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Networking & Cloud Computing, Security', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Networking & Cloud Computing, Software', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Networks, Protocols & APIs', 64);
INSERT INTO category_info(book_category, book_count) VALUES ('Networks, Protocols & APIs, Certification', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Networks, Protocols & APIs, Cloud & Virtualization', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Networks, Protocols & APIs, Network Security', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('NoSQL', 41);
INSERT INTO category_info(book_category, book_count) VALUES ('NoSQL, Big Data', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Objective-C', 5);
INSERT INTO category_info(book_category, book_count) VALUES ('Office', 155);
INSERT INTO category_info(book_category, book_count) VALUES ('Office, Microsoft', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('OpenCL', 5);
INSERT INTO category_info(book_category, book_count) VALUES ('Operating Systems', 15);
INSERT INTO category_info(book_category, book_count) VALUES ('Operating Systems, Hardware & DIY', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Operating Systems, Hardware & DIY, Security', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Operating Systems, Networking & Cloud Computing', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Oracle', 165);
INSERT INTO category_info(book_category, book_count) VALUES ('Oracle, Certification', 3);
INSERT INTO category_info(book_category, book_count) VALUES ('Oracle, Cloud Computing', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Oracle, Networks, Protocols & APIs', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Oracle, SQL', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Other', 82);
INSERT INTO category_info(book_category, book_count) VALUES ('Perl', 20);
INSERT INTO category_info(book_category, book_count) VALUES ('Photoshop', 19);
INSERT INTO category_info(book_category, book_count) VALUES ('Photoshop, Software', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('PHP', 137);
INSERT INTO category_info(book_category, book_count) VALUES ('PHP, Apps', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('PHP, CMS', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('PHP, Game Programming', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('PHP, jQuery', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('PHP, MySQL', 17);
INSERT INTO category_info(book_category, book_count) VALUES ('PHP, Services & APIs', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('PHP, Windows & PC', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('PostgreSQL', 18);
INSERT INTO category_info(book_category, book_count) VALUES ('PowerShell', 19);
INSERT INTO category_info(book_category, book_count) VALUES ('Premiere', 3);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming', 434);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, 3D Graphics', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Administration', 3);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, AI & Machine Learning', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Android', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Computer Science', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Data Analysis', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Data Mining', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Graphics & Design', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Hardware & DIY', 5);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, iOS', 4);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, JavaScript', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Linux & Unix', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Macintosh', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Microsoft', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Networking & Cloud Computing', 3);
INSERT INTO category_info(book_category, book_count) VALUES ('Programming, Office', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python', 255);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Algorithms', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, C & C++, C#', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Cloud & Virtualization', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Cloud Computing', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Data Analysis', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Data Mining', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Data Processing', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Datebases', 4);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Game Programming', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Graphics & Design', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Hardware & DIY', 5);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Java', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Network Security', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Networks, Protocols & APIs', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Operating Systems', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Security', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Python, Web Servers', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Rails', 35);
INSERT INTO category_info(book_category, book_count) VALUES ('Ruby', 77);
INSERT INTO category_info(book_category, book_count) VALUES ('Ruby, Network Administration', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Scala', 17);
INSERT INTO category_info(book_category, book_count) VALUES ('Security', 150);
INSERT INTO category_info(book_category, book_count) VALUES ('Security, Certification', 3);
INSERT INTO category_info(book_category, book_count) VALUES ('Security, iOS', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Services & APIs', 64);
INSERT INTO category_info(book_category, book_count) VALUES ('SharePoint', 77);
INSERT INTO category_info(book_category, book_count) VALUES ('SOA', 16);
INSERT INTO category_info(book_category, book_count) VALUES ('Software', 110);
INSERT INTO category_info(book_category, book_count) VALUES ('Software, Administration', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Software, Game Programming', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Software, Windows & PC', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('SQL', 126);
INSERT INTO category_info(book_category, book_count) VALUES ('SQL, Data Mining', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('SQL, Data Processing, Data Mining', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('SQL, Hardware & DIY', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('SQL, Networking & Cloud Computing', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Swift', 68);
INSERT INTO category_info(book_category, book_count) VALUES ('Task Automation', 16);
INSERT INTO category_info(book_category, book_count) VALUES ('Testing & Engineering', 6);
INSERT INTO category_info(book_category, book_count) VALUES ('Theory', 14);
INSERT INTO category_info(book_category, book_count) VALUES ('Visual Basic', 18);
INSERT INTO category_info(book_category, book_count) VALUES ('Visual Basic, .NET', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Web Design', 39);
INSERT INTO category_info(book_category, book_count) VALUES ('Web Development', 167);
INSERT INTO category_info(book_category, book_count) VALUES ('Web Development, Administration', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Web Development, Game Programming', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Web Development, Networking & Cloud Computing', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Web Servers', 23);
INSERT INTO category_info(book_category, book_count) VALUES ('Web Services', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Windows', 91);
INSERT INTO category_info(book_category, book_count) VALUES ('Windows & PC', 60);
INSERT INTO category_info(book_category, book_count) VALUES ('Windows & PC, Certification', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Windows Phone', 23);
INSERT INTO category_info(book_category, book_count) VALUES ('Windows, Certification', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Windows, Game Programming', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Windows, Hardware & DIY', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Windows, Linux & Unix', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Windows, Microsoft', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Windows, Network Administration', 2);
INSERT INTO category_info(book_category, book_count) VALUES ('Wireless Networks', 8);
INSERT INTO category_info(book_category, book_count) VALUES ('Wireless Networks, Cisco', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('Wireless Networks, Data in the Enterprise', 1);
INSERT INTO category_info(book_category, book_count) VALUES ('XML', 25);